-- 1. Vendor Performance Analysis
-- 1) Total revenue generated by each vendor
SELECT
    v.vendor_id,
    v.vendor_name,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount / 100.0)), 2) AS total_revenue
FROM vendors v
JOIN products p
    ON v.vendor_id = p.vendor_id
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY v.vendor_id, v.vendor_name
ORDER BY total_revenue DESC;

-- 2) Rank vendors based on total revenue generated
WITH vendor_revenue AS (
    SELECT
        v.vendor_id,
        v.vendor_name,
        ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount / 100.0)), 2) AS total_revenue
    FROM vendors v
    JOIN products p
        ON v.vendor_id = p.vendor_id
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY v.vendor_id, v.vendor_name
)
SELECT
    vendor_id,
    vendor_name,
    total_revenue,
    RANK() OVER (ORDER BY total_revenue DESC) AS vendor_rank
FROM vendor_revenue
ORDER BY vendor_rank;

-- 3) Vendors generating revenue above average vendor revenue
WITH vendor_revenue AS (
    SELECT
        v.vendor_id,
        v.vendor_name,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount / 100.0)) AS total_revenue
    FROM vendors v
    JOIN products p
        ON v.vendor_id = p.vendor_id
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY v.vendor_id, v.vendor_name
)
SELECT
    vendor_id,
    vendor_name,
    ROUND(total_revenue, 2) AS total_revenue
FROM vendor_revenue
WHERE total_revenue > (
    SELECT AVG(total_revenue)
    FROM vendor_revenue
)
ORDER BY total_revenue DESC;

-- 4) How many active products each vendor currently sells
SELECT
    v.vendor_id,
    v.vendor_name,
    COUNT(p.product_id) AS active_product_count
FROM vendors v
LEFT JOIN products p
    ON v.vendor_id = p.vendor_id
   AND p.status = 'Active'
GROUP BY v.vendor_id, v.vendor_name
ORDER BY active_product_count DESC, v.vendor_name;

-- 5) Vendors selling products across multiple categories
SELECT
    v.vendor_id,
    v.vendor_name,
    COUNT(DISTINCT p.category_id) AS category_count
FROM vendors v
JOIN products p
    ON v.vendor_id = p.vendor_id
GROUP BY v.vendor_id, v.vendor_name
HAVING COUNT(DISTINCT p.category_id) > 1
ORDER BY category_count DESC, v.vendor_name;

